Repository googleapis/java-tasks, pull requests merged in 2020-09, with the labels that each got.

#212 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: cloudtasks, automerge, cla: yes, context: full

#218 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: cloudtasks, cla: yes, context: full

#221 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#233 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#237 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: cloudtasks, automerge, cla: yes

#242 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: api: cloudtasks, automerge, cla: yes, context: full

#244 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
