Repository googleapis/java-tasks, pull requests merged in 2020-06, with the labels that each got.

#153 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#144 fix: restore GAPIC v2 retry configs
  google-cloud-tasks/src/main/java/com/google/cloud/tasks/v2beta2/stub/CloudTasksStubSettings.java
  google-cloud-tasks/src/main/java/com/google/cloud/tasks/v2beta3/stub/CloudTasksStubSettings.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#156 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#158 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#160 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#165 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#169 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#175 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-tasks/pom.xml
  grpc-google-cloud-tasks-v2/pom.xml
  grpc-google-cloud-tasks-v2beta2/pom.xml
  grpc-google-cloud-tasks-v2beta3/pom.xml
  pom.xml
  proto-google-cloud-tasks-v2/pom.xml
  proto-google-cloud-tasks-v2beta2/pom.xml
  proto-google-cloud-tasks-v2beta3/pom.xml
Labels: cla: yes

#174 fix: migrate retry settings to grpc_service_config
  README.md
  google-cloud-tasks/src/main/java/com/google/cloud/tasks/v2/stub/CloudTasksStubSettings.java
  google-cloud-tasks/src/main/java/com/google/cloud/tasks/v2beta2/stub/CloudTasksStubSettings.java
  google-cloud-tasks/src/main/java/com/google/cloud/tasks/v2beta3/stub/CloudTasksStubSettings.java
  synth.metadata
Labels: automerge, cla: yes, context: partial

#181 feat(v2beta3): add type to Queue
  README.md
  proto-google-cloud-tasks-v2beta2/clirr-ignored-differences.xml
  proto-google-cloud-tasks-v2beta3/clirr-ignored-differences.xml
  proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/AppEngineHttpRequest.java
  proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/AppEngineHttpRequestOrBuilder.java
  proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/Queue.java
  proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/QueueOrBuilder.java
  proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/QueueProto.java
  proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/RetryConfig.java
  proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/RetryConfigOrBuilder.java
  proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/Task.java
  proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/TaskOrBuilder.java
  proto-google-cloud-tasks-v2beta3/src/main/proto/google/cloud/tasks/v2beta3/cloudtasks.proto
  proto-google-cloud-tasks-v2beta3/src/main/proto/google/cloud/tasks/v2beta3/queue.proto
  proto-google-cloud-tasks-v2beta3/src/main/proto/google/cloud/tasks/v2beta3/target.proto
  proto-google-cloud-tasks-v2beta3/src/main/proto/google/cloud/tasks/v2beta3/task.proto
  synth.metadata
Labels: automerge, cla: yes, context: partial

#188 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
