Repository googleapis/java-tasks, pull requests merged in 2020-11, with the labels that each got.

#291 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#293 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#275 Update region tag
  samples/install-without-bom/pom.xml
Labels: api: cloudtasks, cla: yes

#276 Update region tag
  samples/snippets/pom.xml
Labels: api: cloudtasks, cla: yes

#294 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtasks, automerge, cla: yes

#296 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: cloudtasks, automerge, cla: yes, context: full

#298 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: cloudtasks, automerge, cla: yes, context: full

#304 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: cloudtasks, automerge, cla: yes, context: full

#307 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: cloudtasks, automerge, cla: yes, context: full

#309 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtasks, cla: yes
