Repository googleapis/java-tasks, pull requests merged in 2021-09, with the labels that each got.

#499 chore: update gapic-generator-java version to 2.1.0
  google-cloud-tasks/src/main/java/com/google/cloud/tasks/v2/stub/CloudTasksStubSettings.java
  google-cloud-tasks/src/main/java/com/google/cloud/tasks/v2beta2/stub/CloudTasksStubSettings.java
  google-cloud-tasks/src/main/java/com/google/cloud/tasks/v2beta3/stub/CloudTasksStubSettings.java
  synth.metadata
Labels: cla: yes, api: cloudtasks, automerge, context: full

#510 chore: re-generated to pick up changes from synthtool
  .github/workflows/ci.yaml
  renovate.json
  synth.metadata
Labels: cla: yes, api: cloudtasks, context: full

#515 chore(java): install maven 3.8.1 at runtime
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, kokoro:force-run, api: cloudtasks, automerge, context: full

#514 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: cloudtasks, automerge

#516 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  google-cloud-tasks-bom/pom.xml
  google-cloud-tasks/pom.xml
  owlbot.py
  pom.xml
  samples/snippets/src/main/java/com/example/task/CreateHttpTaskWithToken.java
  samples/snippets/src/main/java/com/example/task/ListQueues.java
  samples/snippets/src/test/java/com/example/task/DeleteQueueIT.java
  samples/snippets/src/test/java/com/example/task/ListQueuesIT.java
  synth.py
  versions.txt
Labels: cla: yes, api: cloudtasks, automerge

#523 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, api: cloudtasks, automerge

#539 chore: change branch master to main in github configurations
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: cloudtasks, automerge

#529 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: cloudtasks
