Repository googleapis/java-tasks, pull requests merged in 2021-05, with the labels that each got.

#427 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: cloudtasks, automerge, cla: yes, context: none

#428 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: cloudtasks, automerge, cla: yes

#429 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudtasks, cla: yes, context: full

#433 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtasks, automerge, cla: yes

#434 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: cloudtasks, automerge, cla: yes, context: full

#436 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudtasks, automerge, cla: yes, context: full

#438 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: cloudtasks, automerge, cla: yes, context: full

#444 docs: fix grammar in documentation.
  proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/Queue.java
  proto-google-cloud-tasks-v2beta2/src/main/java/com/google/cloud/tasks/v2beta2/QueueOrBuilder.java
  proto-google-cloud-tasks-v2beta2/src/main/proto/google/cloud/tasks/v2beta2/queue.proto
  proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/Queue.java
  proto-google-cloud-tasks-v2beta3/src/main/java/com/google/cloud/tasks/v2beta3/QueueOrBuilder.java
  proto-google-cloud-tasks-v2beta3/src/main/proto/google/cloud/tasks/v2beta3/queue.proto
  synth.metadata
Labels: api: cloudtasks, cla: yes, context: full
